export const DEFAULT_COLORS = [
  { name: 'Negro', hex: '#000000' },
  { name: 'Blanco', hex: '#FFFFFF' },
  { name: 'Gris', hex: '#808080' },
  { name: 'Plateado', hex: '#C0C0C0' },
  { name: 'Rojo', hex: '#FF0000' },
  { name: 'Bordó', hex: '#800020' },
  { name: 'Naranja', hex: '#FFA500' },
  { name: 'Amarillo', hex: '#FFFF00' },
  { name: 'Dorado', hex: '#FFD700' },
  { name: 'Verde', hex: '#008000' },
  { name: 'Verde lima', hex: '#00FF00' },
  { name: 'Oliva', hex: '#808000' },
  { name: 'Turquesa', hex: '#40E0D0' },
  { name: 'Celeste', hex: '#87CEEB' },
  { name: 'Azul', hex: '#0000FF' },
  { name: 'Azul marino', hex: '#000080' },
  { name: 'Violeta', hex: '#800080' },
  { name: 'Rosa', hex: '#FFC0CB' },
  { name: 'Marrón', hex: '#8B4513' },
  { name: 'Beige', hex: '#F5F5DC' },
] as const;
